name: linebacker
baseurl: /linebacker
description: Thread Pool Management for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
